LT-2752 Unhardcode EUR
lykkecloud/MarginTrading.CommissionService pull request #116
Opened 2020-11-09 14:12 UTC by IliyanIlievPH

2020-11-09 15:39 UTC, tarurar submitted a review, later dismissed

2020-12-08 07:59 UTC, andrey-anokhin requested changes

2020-12-08 07:59 UTC, andrey-anokhin commented on src/MarginTrading.CommissionService.Services/BrokerSettingsService.cs
> +            return brokerSettings.BrokerSettings.SettlementCurrency;
I think we should cache the value as we do in the Asset Service. Otherwise, we will make this call for every instrument, meaning more than 1000 calls in a row, during the EOD.

2020-12-08 08:13 UTC, andrey-anokhin approved these changes

2020-12-08 08:14 UTC, merged